// Generated by scripts/build-client.mjs from lib/** — do not edit by hand.
// Bundle id must equal the package name (the Harness keys the client module table by package name).
window.__ModuleLoader__.load({
  id: "dsh-notifications",
  factory: (require) => {
    const module = { exports: {} }
    const exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })
    // ---- lib/shared/contract.js ----
/**
 * Shared contract between the plugin's host half and its browser bundle.
 *
 * Both halves must agree on three things: which attentions the Harness can
 * raise, which notification categories the settings page exposes, and how a
 * keyword rule line is spelled. Keeping the answers here — dependency-free and
 * side-effect-free — is what lets the host read the profile Config while the
 * bundle reads the same fields through `configForms`, without either half
 * guessing at the other's vocabulary.
 */

/** Pending interactions the Harness client reports for a session. */
const PENDING_KINDS = Object.freeze(['approval', 'question', 'plan-review'])

/** Turn-end reasons a completion notification can report. */
const TURN_REASONS = Object.freeze(['completed', 'error', 'aborted', 'blocked', 'max-tokens'])

/**
 * Profile-config fields this plugin reads, with the fallback for a value the
 * profile does not carry (an older patch layer, or a partially written form).
 * The host declares the same names in its schemastery `Config`; this map is the
 * single list the browser bundle validates against.
 */
const SETTING_DEFAULTS = Object.freeze({
  // Native side: the macOS menu bar indicator.
  enabled: true,
  questionMarkers: true,
  approvalMarkers: true,
  sweep: true,
  sound: true,
  flash: true,
  // Browser side: system notifications from the Web Client half.
  browserNotifications: true,
  notifyApproval: true,
  notifyQuestion: true,
  notifyPlanReview: false,
  notifyCompleted: true,
  notifyError: true,
  backgroundOnly: true,
  requireInteraction: false,
  keywords: '',
})

/** Whether a value is a plain boolean. */
function isBoolean(value) {
  return typeof value === 'boolean'
}

/**
 * Fold a raw settings snapshot into the field map both halves use. Unknown keys
 * are dropped and wrong-typed values fall back to the declared default, so a
 * hand-edited patch layer can never make the bundle throw.
 * @param raw - the profile form value (or any object).
 * @returns a complete settings record.
 */
function resolveSettings(raw) {
  const source = raw !== null && typeof raw === 'object' ? raw : {}
  const resolved = {}
  for (const [field, fallback] of Object.entries(SETTING_DEFAULTS)) {
    const value = source[field]
    if (isBoolean(fallback)) resolved[field] = isBoolean(value) ? value : fallback
    else resolved[field] = typeof value === 'string' ? value : fallback
  }
  return resolved
}

/** The notification category for one pending interaction kind. */
function pendingCategory(kind) {
  switch (kind) {
    case 'approval': return 'notifyApproval'
    case 'question': return 'notifyQuestion'
    case 'plan-review': return 'notifyPlanReview'
    default: return undefined
  }
}

/** The notification category for one turn-end reason. */
function completionCategory(reason) {
  switch (reason) {
    case 'completed': return 'notifyCompleted'
    case 'error': return 'notifyError'
    default: return undefined
  }
}

/**
 * Normalize a raw pending-interaction kind reported by the Harness client.
 * @param value - the reported `pendingInteraction.kind`.
 * @returns the known kind, or undefined for anything else.
 */
function asPendingKind(value) {
  return typeof value === 'string' && PENDING_KINDS.includes(value) ? value : undefined
}

/**
 * Normalize a raw turn-end reason.
 * @param value - the reported reason kind.
 * @returns the known reason, or undefined for anything else.
 */
function asTurnReason(value) {
  return typeof value === 'string' && TURN_REASONS.includes(value) ? value : undefined
}

    // ---- lib/shared/decision.js ----
/**
 * The notification decision, shared by the host half and the browser bundle.
 *
 * Everything here is pure: it maps an attention to a category, evaluates the
 * keyword rules over a subject string, and answers whether that attention
 * should surface. Browser permission, page visibility and the native helper
 * stay outside — those are reads with side effects, and keeping them out is
 * what makes this file testable without a DOM.
 */
/** The keyword-rule marker that turns a line into an exclusion. */
const EXCLUDE_PREFIX = '-'
/** The keyword-rule marker that turns a line into a regular expression. */
const REGEX_PREFIX = 're:'
/** The keyword-rule marker that makes a match case-sensitive. */
const CASE_PREFIX = 'cs:'

/**
 * Parse the settings page's keyword text into rules.
 *
 * Grammar, one rule per line:
 *   `word`        include when the subject contains `word`
 *   `-word`       exclude when the subject contains `word`
 *   `re:pattern`  include when the regular expression matches
 *   `-re:pattern` exclude when the regular expression matches
 *   `cs:` prefix (after the include/exclude marker) makes matching case-sensitive
 *
 * Blank lines are ignored, matching is case-insensitive unless `cs:` is given,
 * and a malformed regular expression degrades to an inert rule rather than
 * throwing — a settings typo must never disable notifications wholesale.
 * @param text - the raw keyword field.
 * @returns parsed rules in declaration order.
 */
function parseKeywordRules(text) {
  if (typeof text !== 'string' || text.trim() === '') return []
  const rules = []
  for (const line of text.split('\n')) {
    let body = line.trim()
    if (body === '') continue
    let mode = 'include'
    if (body.startsWith(EXCLUDE_PREFIX)) {
      mode = 'exclude'
      body = body.slice(EXCLUDE_PREFIX.length).trim()
    }
    let caseSensitive = false
    if (body.startsWith(CASE_PREFIX)) {
      caseSensitive = true
      body = body.slice(CASE_PREFIX.length)
    }
    const isRegex = body.startsWith(REGEX_PREFIX)
    const pattern = isRegex ? body.slice(REGEX_PREFIX.length) : body
    if (pattern === '') continue
    if (isRegex) {
      try {
        // Compile once at parse time so a bad pattern is inert for its whole life.
        new RegExp(pattern, caseSensitive ? '' : 'i')
      } catch {
        rules.push({ mode, pattern, isRegex, caseSensitive, invalid: true })
        continue
      }
    }
    rules.push({ mode, pattern, isRegex, caseSensitive, invalid: false })
  }
  return rules
}

/**
 * Whether one rule matches a subject.
 * @param rule - a rule from {@link parseKeywordRules}.
 * @param subject - the text a rule is matched against.
 * @returns true when the rule matches.
 */
function ruleMatches(rule, subject) {
  if (rule.invalid === true) return false
  if (rule.isRegex) {
    return new RegExp(rule.pattern, rule.caseSensitive ? '' : 'i').test(subject)
  }
  const haystack = rule.caseSensitive ? subject : subject.toLowerCase()
  const needle = rule.caseSensitive ? rule.pattern : rule.pattern.toLowerCase()
  return haystack.includes(needle)
}

/**
 * Evaluate include/exclude rules over one subject.
 *
 * Exclusions always win. When at least one include rule is configured, the
 * subject must match one of them; with no include rules everything is allowed.
 * @param rules - parsed keyword rules.
 * @param subject - the text to judge.
 * @returns whether a notification may surface for this subject.
 */
function rulesAllow(rules, subject) {
  if (rules.length === 0) return true
  const excludes = rules.filter(rule => rule.mode === 'exclude')
  if (excludes.some(rule => ruleMatches(rule, subject))) return false
  const includes = rules.filter(rule => rule.mode === 'include')
  if (includes.length === 0) return true
  return includes.some(rule => ruleMatches(rule, subject))
}

/**
 * Build the text keyword rules are matched against: the session title, the
 * attention's detail (tool name or question text), and any turn reply body.
 * @param title - the session title, when the runtime projects one.
 * @param detail - the attention-specific detail line.
 * @param body - a turn's reply text, when one is being reported.
 * @returns the joined subject.
 */
function ruleSubject(title, detail, body) {
  const parts = []
  if (typeof title === 'string' && title.trim() !== '') parts.push(title.trim())
  if (typeof detail === 'string' && detail.trim() !== '') parts.push(detail.trim())
  if (typeof body === 'string' && body.trim() !== '') parts.push(body.trim())
  return parts.join('\n')
}

/**
 * Whether the settings enable the notification category for one attention.
 * @param settings - a resolved settings record.
 * @param category - the category field name.
 * @returns whether this category is on.
 */
function categoryEnabled(settings, category) {
  if (category === undefined) return false
  if (settings.enabled !== true) return false
  if (settings.browserNotifications !== true) return false
  return settings[category] === true
}

/** The attention categories this plugin can raise, in settings-page order. */
const ATTENTION_KINDS = Object.freeze(['approval', 'question', 'plan-review', 'completed', 'error'])

/**
 * Decide one attention end to end: category, settings, and keyword rules.
 * @param settings - a resolved settings record.
 * @param kind - a pending kind or turn reason.
 * @param title - the session title.
 * @param detail - the attention detail line.
 * @param body - an optional reply body.
 * @returns whether to notify.
 */
function shouldNotify(settings, kind, title, detail, body) {
  const category = pendingCategory(kind) ?? completionCategory(kind)
  if (!categoryEnabled(settings, category)) return false
  const rules = parseKeywordRules(settings.keywords)
  return rulesAllow(rules, ruleSubject(title, detail, body))
}

/** Convenience for callers holding raw profile values. */

    // ---- lib/client/notifier.js ----
// Browser-side notification delivery.
//
// Fragment: concatenated into the plugin bundle by scripts/build-client.mjs, so
// it declares no imports and no exports and shares one scope with the shared
// contract/decision modules that precede it. Only pure presentation decisions
// live here; the runner owns when to call them.

/** The Notification constructor, or undefined in a context that has none. */
function notificationsApi() {
  return typeof Notification === 'undefined' ? undefined : Notification
}

/** The current browser permission, defaulting to denied without an API. */
function notificationPermission() {
  return notificationsApi()?.permission ?? 'denied'
}

/** Ask the browser for notification permission, tolerating an absent API. */
function requestNotificationPermission() {
  const api = notificationsApi()
  if (api === undefined) return Promise.resolve('denied')
  try {
    return Promise.resolve(api.requestPermission())
  } catch (error) {
    return Promise.reject(error)
  }
}

/**
 * The notification title key for one attention kind. Titles are looked up in
 * the locale dictionary by the runner, never composed here.
 */
function attentionTitleKey(kind) {
  switch (kind) {
    case 'approval': return 'titleApproval'
    case 'question': return 'titleQuestion'
    case 'plan-review': return 'titlePlanReview'
    case 'completed': return 'titleCompleted'
    case 'error': return 'titleError'
    default: return 'titleGeneric'
  }
}

/**
 * Whether a notification may surface right now.
 *
 * Permission is mandatory. `backgroundOnly` keeps a notification from firing
 * for the session the user is already looking at in a focused page: a
 * completion or an approval the user can already see on screen does not need a
 * system banner, and firing one there is how a notifier becomes noise.
 * @param permission - the browser permission.
 * @param backgroundOnly - the "only when the page is not in front" setting.
 * @param documentHidden - whether the page is currently hidden.
 * @param sessionId - the session the attention belongs to.
 * @param currentSessionId - the session currently in view.
 * @returns whether to show.
 */
function shouldShowNotification(permission, backgroundOnly, documentHidden, sessionId, currentSessionId) {
  if (permission !== 'granted') return false
  if (backgroundOnly === true && documentHidden !== true && sessionId === currentSessionId) return false
  return true
}

/**
 * The grouping tag for one attention. One slot per session per attention
 * sequence keeps a later banner from being swallowed by an earlier one that is
 * still sitting in the notification centre.
 */
function notificationTag(sessionId, kind, sequence) {
  return `dsh-notifications-${kind}-${sessionId}-${sequence}`
}

/**
 * Construct one system notification and wire its click to focus the window.
 * @returns a result record; creation failures are reported, never swallowed.
 */
function showNotification(title, body, tag, requireInteraction) {
  const api = notificationsApi()
  if (api === undefined) return { ok: false, message: 'The Notification API is unavailable in this context.' }
  if (api.permission !== 'granted') return { ok: false, message: 'Notification permission is not granted.' }
  try {
    const notification = new api(title, { body, tag, requireInteraction })
    notification.onclick = () => { try { window.focus() } catch { /* focus is best effort */ } }
    return { ok: true, notification }
  } catch (error) {
    return { ok: false, message: error instanceof Error ? error.message : String(error) }
  }
}

    // ---- lib/client/runner.js ----
// The attention runners: the browser half's reason to exist.
//
// Two observations drive every notification:
//   1. a session's pending interaction (`approval` / `question` / `plan-review`)
//      appearing — this is what fires when the Harness needs YOU, including a
//      sandbox escalation;
//   2. a session's completion flag going unread — a turn just finished.
//
// Both come from `uiSession.sessionStatus`, the live client-side truth the
// Harness itself renders from. That matters: the reference implementation this
// plugin learned from reads `uiSession.pendingInteractions`, a name that does
// not exist in DSH 0.2.0-rc.1 — a runner copied from it would observe nothing
// and stay silent, which is exactly the bug this file exists to fix.
//
// Fragment: concatenated by scripts/build-client.mjs; no imports or exports.

/** Fold one session's pending kind and report whether a fresh wait appeared. */
function pendingAdvance(previous, kind) {
  if (previous === undefined) return { kind, fresh: false }
  return { kind, fresh: kind !== undefined && kind !== previous.kind }
}

/** Fold one session's unread-completion flag and report the rising edge. */
function completionAdvance(previous, unread) {
  if (previous === undefined) return { unread, fresh: false }
  return { unread, fresh: unread === true && previous !== true }
}

/**
 * Read the session status map across both shapes the client has used: the
 * 0.1.x row field and the 0.2 status store. Reading defensively keeps one
 * bundle working on both generations — the failure mode this plugin actually
 * shipped with was reading only the shape that had gone away.
 *
 * The check is structural rather than `instanceof Map`: the bundle is evaluated
 * in its own realm, where a map handed in from another realm fails an
 * `instanceof` test while still being a perfectly good map.
 * @returns the status map, or an empty map when the service is absent.
 */
function sessionStatusMap(uiSession) {
  const store = uiSession?.sessionStatus
  if (store === undefined || typeof store.getSnapshot !== 'function') return new Map()
  const snapshot = store.getSnapshot()
  if (snapshot === null || typeof snapshot !== 'object' || typeof snapshot.get !== 'function') return new Map()
  return snapshot
}

/** The pending kind reported for one session, across both client generations. */
function pendingKindOf(statusMap, summary) {
  const fromStatus = asPendingKind(statusMap.get(summary.id)?.pendingInteraction?.kind)
  if (fromStatus !== undefined) return fromStatus
  return asPendingKind(summary.pendingInteraction)
}

/** Whether one session's completion is unread, across both client generations. */
function completionUnreadOf(statusMap, summary) {
  const status = statusMap.get(summary.id)
  if (status !== undefined && typeof status.completionUnread === 'boolean') return status.completionUnread
  return summary.completed === true
}

/**
 * The detail line for one attention: the tool asking for approval, or the
 * session title, whichever the runtime actually supplies.
 */
function attentionDetail(kind, status, title) {
  const interaction = status?.pendingInteraction
  if (kind === 'approval') {
    const tool = typeof interaction?.toolName === 'string' && interaction.toolName !== ''
      ? interaction.toolName
      : undefined
    const reason = typeof interaction?.displayReason === 'string' && interaction.displayReason !== ''
      ? interaction.displayReason
      : (typeof interaction?.reason === 'string' ? interaction.reason : undefined)
    return [tool, reason].filter(part => part !== undefined && part !== '').join(' · ')
  }
  return typeof title === 'string' ? title : ''
}

/**
 * Start both runners. Returns a disposer; every subscription is released with
 * the plugin's fiber.
 *
 * @param deps - the wired dependencies (all optional except `settings`).
 * @returns the disposer.
 */
function startAttentionRunners(deps) {
  const { settings, uiSession, sessions, translate, notify } = deps
  const observedPending = new Map()
  const observedCompletion = new Map()
  const sequences = new Map()

  const readSettings = () => {
    const snapshot = settings.getSnapshot()
    return resolveSettings(snapshot?.value)
  }

  const listSnapshot = () => {
    const list = sessions?.list
    if (list === undefined || typeof list.getSnapshot !== 'function') return { ids: [], byId: {}, current: undefined }
    return list.getSnapshot() ?? { ids: [], byId: {}, current: undefined }
  }

  /** Judge one attention and hand a decided plan to the notifier. */
  const raise = (kind, sessionId, title, detail) => {
    const current = readSettings()
    if (!shouldNotify(current, kind, title, detail, '')) return
    const sequence = (sequences.get(`${sessionId}:${kind}`) ?? 0) + 1
    sequences.set(`${sessionId}:${kind}`, sequence)
    notify({
      kind,
      sessionId,
      title: translate(attentionTitleKey(kind)),
      body: detail === '' ? translate('bodyFallback') : detail,
      tag: notificationTag(sessionId, kind, sequence),
      requireInteraction: current.requireInteraction === true,
    })
  }

  const run = () => {
    const list = listSnapshot()
    const statusMap = sessionStatusMap(uiSession)
    const live = new Set()

    for (const id of list.ids ?? []) {
      const summary = list.byId?.[id]
      if (summary === undefined) continue
      live.add(id)
      const status = statusMap.get(id)
      const title = summary.displayTitle ?? summary.title

      const pending = pendingAdvance(observedPending.get(id), pendingKindOf(statusMap, summary))
      // Store a wrapper, never the bare kind: `Map.get` answers undefined both
      // for "never observed" and for "observed, nothing pending", and conflating
      // the two makes the first real wait look like a seed and never fire.
      observedPending.set(id, { kind: pending.kind })
      if (pending.fresh && pending.kind !== undefined) {
        raise(pending.kind, id, title, attentionDetail(pending.kind, status, title))
      }

      const completion = completionAdvance(observedCompletion.get(id), completionUnreadOf(statusMap, summary))
      observedCompletion.set(id, { unread: completion.unread })
      if (completion.fresh) {
        // A session that is waiting for the user is not "finished": the
        // completion flag and a pending interaction can be set at once, and the
        // approval banner is the one that matters.
        if (pendingKindOf(statusMap, summary) === undefined) {
          raise('completed', id, title, title ?? '', '')
        }
      }
    }

    for (const id of [...observedPending.keys()]) if (!live.has(id)) observedPending.delete(id)
    for (const id of [...observedCompletion.keys()]) if (!live.has(id)) observedCompletion.delete(id)
  }

  /** Forget every observation; the next frame seeds a fresh baseline. */
  const reseed = () => {
    observedPending.clear()
    observedCompletion.clear()
    run()
  }

  // Seed before subscribing: a wait or a completion that already existed when
  // the page loaded is history, not news.
  run()

  const disposers = []
  const statusStore = uiSession?.sessionStatus
  if (statusStore !== undefined && typeof statusStore.subscribe === 'function') {
    disposers.push(statusStore.subscribe(run))
  }
  const list = sessions?.list
  if (list !== undefined && typeof list.subscribe === 'function') disposers.push(list.subscribe(run))
  return { dispose: () => { for (const off of disposers) { try { off() } catch { /* already released */ } } }, reseed, run }
}

    // ---- lib/client/locales.js ----
// Locale dictionaries for the settings page and the notifications it raises.
// Fragment: concatenated into the bundle; no imports or exports.

const dictionaries = {
  zh: {
    nav: '通知',
    title: '通知',
    intro: '管理 macOS 菜单栏状态项，以及 Harness 需要你处理时的系统通知。',
    groupNative: '菜单栏状态项',
    groupBrowser: '系统通知',
    groupRules: '关键词规则',
    label: '显示菜单栏状态项',
    description: '显示鲸鱼图标和当前进行中的会话数。',
    soundLabel: '提醒音',
    soundDescription: '需要授权或回答时播放提示音。',
    flashLabel: '闪烁提醒',
    flashDescription: '需要处理时让菜单栏状态项变红并闪烁，直到事件被处理。',
    subscriptionLabel: '订阅事件类型',
    subscriptionDescription: '数字汇总所有已订阅且等待处理的事件，字母标识事件类型。',
    questionSubscription: 'Q · 提问',
    approvalSubscription: 'S · 审批',
    sweepLabel: '扫光强化提示',
    sweepDescription: '等待回答时，为菜单栏状态项添加扫光效果。',
    browserLabel: '弹出系统通知',
    browserDescription: 'Harness 需要你处理、或一轮任务结束时，弹出 macOS 通知。',
    notifyApproval: '需要授权时提醒',
    notifyApprovalDescription: '工具请求提权、沙箱需要放行时立即提醒 —— 这是最容易错过的一类。',
    notifyQuestion: '需要回答时提醒',
    notifyQuestionDescription: '模型提问等待你作答时提醒。',
    notifyPlanReview: '计划待审阅时提醒',
    notifyPlanReviewDescription: '计划模式等待你确认时提醒。',
    notifyCompleted: '任务完成时提醒',
    notifyCompletedDescription: '会话结束一轮任务时提醒。',
    notifyError: '任务出错时提醒',
    notifyErrorDescription: '一轮任务以错误结束时提醒。',
    backgroundOnly: '只在不在前台时提醒',
    backgroundOnlyDescription: '正在看这个会话、且页面在前台时不打扰你。',
    requireInteraction: '通知保持显示',
    requireInteractionDescription: '通知不会自动消失，直到你手动关闭。',
    keywordsLabel: '关键词规则',
    keywordsDescription: '一行一条。默认是"包含才提醒"；前缀 - 表示排除，re: 表示正则，cs: 区分大小写。留空表示不过滤。',
    keywordsPlaceholder: '例如：\n-沙箱测试\nre:^部署',
    permissionGranted: '浏览器通知权限：已授权',
    permissionDenied: '浏览器通知权限：未授权',
    permissionUnavailable: '当前环境不支持系统通知',
    grant: '授权',
    test: '发送测试通知',
    testTitle: 'DSH 通知测试',
    testBody: '如果你看到这条通知，说明系统通知已经工作。',
    enabled: '已开启',
    disabled: '已关闭',
    loading: '正在读取设置…',
    unavailable: '当前连接无法管理此设置',
    readOnly: '设置文件为只读',
    toggle: '显示菜单栏状态项',
    questionToggle: '订阅提问事件',
    approvalToggle: '订阅审批事件',
    sweepToggle: '扫光强化提示',
    titleApproval: '需要授权',
    titleQuestion: '需要你回答',
    titlePlanReview: '计划待审阅',
    titleCompleted: '任务已完成',
    titleError: '任务出错',
    titleGeneric: 'Harness 需要你处理',
    bodyFallback: '打开 DeepSeek Harness 查看详情。',
  },
  en: {
    nav: 'Notifications',
    title: 'Notifications',
    intro: 'Manage the macOS menu bar indicator and the system notifications raised when the Harness needs you.',
    groupNative: 'Menu bar indicator',
    groupBrowser: 'System notifications',
    groupRules: 'Keyword rules',
    label: 'Show menu bar status',
    description: 'Show the whale mark and the number of sessions currently in progress.',
    soundLabel: 'Alert sound',
    soundDescription: 'Play a sound when an approval or a question needs you.',
    flashLabel: 'Flashing alert',
    flashDescription: 'Turn the menu bar item red and flash it until the event is handled.',
    subscriptionLabel: 'Subscribed event types',
    subscriptionDescription: 'The number totals subscribed pending events; letters identify their types.',
    questionSubscription: 'Q · Question',
    approvalSubscription: 'S · Approval',
    sweepLabel: 'Sweeping attention effect',
    sweepDescription: 'Sweep across the menu bar item while an answer is pending.',
    browserLabel: 'Raise system notifications',
    browserDescription: 'Show a macOS notification when the Harness needs you or a turn finishes.',
    notifyApproval: 'Notify when an approval is needed',
    notifyApprovalDescription: 'Fires the moment a tool asks for privileged execution or the sandbox needs a decision — the one that is easiest to miss.',
    notifyQuestion: 'Notify when an answer is needed',
    notifyQuestionDescription: 'Fires when the model asks you a question.',
    notifyPlanReview: 'Notify on a plan review',
    notifyPlanReviewDescription: 'Fires when plan mode waits for your confirmation.',
    notifyCompleted: 'Notify when a turn finishes',
    notifyCompletedDescription: 'Fires when a session finishes a turn.',
    notifyError: 'Notify when a turn fails',
    notifyErrorDescription: 'Fires when a turn ends in an error.',
    backgroundOnly: 'Only when the page is not in front',
    backgroundOnlyDescription: 'Skip the banner while you are already looking at that session in a focused page.',
    requireInteraction: 'Keep notifications on screen',
    requireInteractionDescription: 'The notification stays until you dismiss it.',
    keywordsLabel: 'Keyword rules',
    keywordsDescription: 'One rule per line. A bare word means "only notify when it matches"; prefix - to exclude, re: for a regular expression, cs: to match case. Empty means no filtering.',
    keywordsPlaceholder: 'for example:\n-debug\nre:^deploy',
    permissionGranted: 'Browser notification permission: granted',
    permissionDenied: 'Browser notification permission: not granted',
    permissionUnavailable: 'This context cannot raise system notifications',
    grant: 'Grant',
    test: 'Send a test notification',
    testTitle: 'DSH notification test',
    testBody: 'If you can see this, system notifications work.',
    enabled: 'On',
    disabled: 'Off',
    loading: 'Loading settings…',
    unavailable: 'This connection cannot manage the setting',
    readOnly: 'The settings document is read-only',
    toggle: 'Show menu bar status',
    questionToggle: 'Subscribe to question events',
    approvalToggle: 'Subscribe to approval events',
    sweepToggle: 'Sweeping attention effect',
    titleApproval: 'Approval needed',
    titleQuestion: 'An answer is needed',
    titlePlanReview: 'Plan review waiting',
    titleCompleted: 'Task finished',
    titleError: 'Task failed',
    titleGeneric: 'The Harness needs you',
    bodyFallback: 'Open DeepSeek Harness for details.',
  },
}

    // ---- lib/client/styles.js ----
// The settings page's stylesheet.
// Fragment: concatenated into the bundle; no imports or exports.

/** Plugin-scoped style element id, also used as the dedupe key. */
const NOTIFY_STYLE_ID = 'dsh-notifications/client.css'

/** Install the stylesheet once per document. */
function adoptStyles() {
  if (typeof document === 'undefined') return
  if (document.querySelector(`style[data-plugin-css=${JSON.stringify(NOTIFY_STYLE_ID)}]`) !== null) return
  const tag = document.createElement('style')
  tag.dataset.plugin = 'dsh-notifications'
  tag.dataset.pluginCss = NOTIFY_STYLE_ID
  tag.textContent = `
    .dshNotifySection{box-sizing:border-box;max-width:720px;color:var(--dsw-alias-label-primary);display:flex;flex-direction:column;gap:16px}
    .dshNotifyHeading{margin:0;font-size:18px;font-weight:600;line-height:28px}
    .dshNotifyIntro{margin:0;color:var(--dsw-alias-label-secondary);font-size:14px;line-height:22px}
    .dshNotifyGroup{display:flex;flex-direction:column;gap:10px}
    .dshNotifyGroupTitle{margin:0;font-size:13px;font-weight:600;color:var(--dsw-alias-label-secondary);letter-spacing:.02em}
    .dshNotifyCard{display:flex;align-items:center;gap:24px;padding:18px 20px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1)}
    .dshNotifyChildCard{margin-left:24px;border-left:3px solid var(--dsw-alias-border-l2)}
    .dshNotifySubscriptions{display:flex;flex-wrap:wrap;gap:14px 20px}
    .dshNotifyCheckbox{display:inline-flex;align-items:center;gap:7px;color:var(--dsw-alias-label-primary);font-size:13px;line-height:20px;cursor:pointer}
    .dshNotifyCheckbox input{width:16px;height:16px;margin:0;accent-color:var(--dsw-alias-brand-primary)}
    .dshNotifyCheckbox:has(input:disabled){color:var(--dsw-alias-label-secondary);cursor:not-allowed;opacity:.6}
    .dshNotifyCopy{min-width:0;display:flex;flex:1;flex-direction:column;gap:3px}
    .dshNotifyLabel{font-size:14px;font-weight:500;line-height:22px}
    .dshNotifyDescription,.dshNotifyStatus{margin:0;color:var(--dsw-alias-label-secondary);font-size:12px;line-height:18px}
    .dshNotifySwitch{box-sizing:border-box;position:relative;width:44px;height:24px;flex:none;padding:2px;border:0;border-radius:12px;background:var(--dsw-alias-border-l3);cursor:pointer;transition:background .15s ease}
    .dshNotifySwitch[aria-checked=true]{background:var(--dsw-alias-brand-primary)}
    .dshNotifySwitch:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:2px}
    .dshNotifySwitch:disabled{cursor:not-allowed;opacity:.5}
    .dshNotifyKnob{display:block;width:20px;height:20px;border-radius:50%;background:var(--dsw-alias-label-primary-foreground);box-shadow:0 1px 3px rgba(0,0,0,.22);transition:transform .15s ease}
    .dshNotifySwitch[aria-checked=true] .dshNotifyKnob{transform:translateX(20px)}
    .dshNotifyField{box-sizing:border-box;width:100%;min-height:88px;padding:10px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:10px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:18px;resize:vertical}
    .dshNotifyField:focus-visible{outline:2px solid var(--dsw-alias-brand-primary);outline-offset:1px}
    .dshNotifyField:disabled{opacity:.6;cursor:not-allowed}
    .dshNotifyActions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}
    .dshNotifyButton{appearance:none;border:1px solid var(--dsw-alias-border-l2);border-radius:9px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font-size:13px;line-height:20px;padding:6px 12px;cursor:pointer}
    .dshNotifyButton:hover:not(:disabled){background:var(--dsw-alias-bg-layer-2)}
    .dshNotifyButton:disabled{opacity:.5;cursor:not-allowed}
    .dshNotifyHint{margin:0;font-size:12px;line-height:18px;color:var(--dsw-alias-label-secondary)}
  `
  document.head.appendChild(tag)
}

    // ---- lib/client/section.js ----
// The Settings page: one section covering the native indicator, the system
// notifications, and the keyword rules that gate them.
//
// Fragment: concatenated into the bundle. `require` here is the Harness client
// module loader's require, in scope inside the plugin factory.
const { jsx, jsxs } = require('react/jsx-runtime')
const React = require('react')

/** One label + description + switch row. */
function NotifyRow({ label, description, checked, disabled, onClick, ariaLabel, child = false }) {
  return jsxs('div', {
    className: `dshNotifyCard${child ? ' dshNotifyChildCard' : ''}`,
    children: [
      jsxs('div', {
        className: 'dshNotifyCopy',
        children: [
          jsx('div', { className: 'dshNotifyLabel', children: label }),
          description === undefined ? null : jsx('p', { className: 'dshNotifyDescription', children: description }),
        ],
      }),
      jsx('button', {
        type: 'button',
        className: 'dshNotifySwitch',
        role: 'switch',
        'aria-checked': checked,
        'aria-label': ariaLabel ?? label,
        disabled,
        onClick,
        children: jsx('span', { className: 'dshNotifyKnob', 'aria-hidden': true }),
      }),
    ],
  })
}

/** One labelled group of rows. */
function NotifyGroup({ title, children }) {
  return jsxs('div', {
    className: 'dshNotifyGroup',
    children: [
      jsx('h3', { className: 'dshNotifyGroupTitle', children: title }),
      ...children,
    ],
  })
}

/** The keyboard/state summary for a settings snapshot. */
function statusText(snapshot, enabled, t) {
  if (snapshot.status === 'loading') return t('loading')
  // Memory mode keeps a remote browser's writes process-local, so it must not
  // present the form as a persisted setting.
  if (snapshot.status !== 'ready' || snapshot.mode === 'memory') return t('unavailable')
  if (!snapshot.writable) return t('readOnly')
  return enabled ? t('enabled') : t('disabled')
}

/** The macOS menu bar half of the settings. */
function NativeGroup({ t, values, disabled, status, set }) {
  const on = values.enabled !== false
  const editable = disabled === false
  return jsx(NotifyGroup, {
    title: t('groupNative'),
    children: [
      jsx(NotifyRow, {
        label: t('label'), description: t('description'), checked: on,
        disabled: !editable, onClick: () => set({ enabled: !on }), ariaLabel: t('toggle'),
      }),
      jsxs('div', {
        className: 'dshNotifyCard dshNotifyChildCard',
        children: [
          jsxs('div', {
            className: 'dshNotifyCopy',
            children: [
              jsx('div', { className: 'dshNotifyLabel', children: t('subscriptionLabel') }),
              jsx('p', { className: 'dshNotifyDescription', children: t('subscriptionDescription') }),
              jsxs('div', {
                className: 'dshNotifySubscriptions',
                children: [
                  jsxs('label', {
                    className: 'dshNotifyCheckbox',
                    children: [
                      jsx('input', {
                        type: 'checkbox',
                        checked: values.questionMarkers !== false,
                        disabled: !editable || !on,
                        'aria-label': t('questionToggle'),
                        onChange: () => set({ questionMarkers: values.questionMarkers === false }),
                      }),
                      t('questionSubscription'),
                    ],
                  }),
                  jsxs('label', {
                    className: 'dshNotifyCheckbox',
                    children: [
                      jsx('input', {
                        type: 'checkbox',
                        checked: values.approvalMarkers !== false,
                        disabled: !editable || !on,
                        'aria-label': t('approvalToggle'),
                        onChange: () => set({ approvalMarkers: values.approvalMarkers === false }),
                      }),
                      t('approvalSubscription'),
                    ],
                  }),
                ],
              }),
              jsx('p', { className: 'dshNotifyStatus', 'aria-live': 'polite', children: statusText(status, on, t) }),
            ],
          }),
        ],
      }),
      jsx(NotifyRow, {
        label: t('soundLabel'), description: t('soundDescription'), checked: values.sound !== false,
        disabled: !editable || !on, onClick: () => set({ sound: values.sound === false }), ariaLabel: t('soundLabel'),
      }),
      jsx(NotifyRow, {
        label: t('flashLabel'), description: t('flashDescription'), checked: values.flash !== false,
        disabled: !editable || !on, onClick: () => set({ flash: values.flash === false }), ariaLabel: t('flashLabel'),
      }),
      jsx(NotifyRow, {
        label: t('sweepLabel'), description: t('sweepDescription'), checked: values.sweep !== false,
        disabled: !editable || !on || (values.questionMarkers === false && values.approvalMarkers === false),
        onClick: () => set({ sweep: values.sweep === false }), ariaLabel: t('sweepToggle'), child: true,
      }),
    ],
  })
}

/** The system-notification half of the settings. */
function BrowserGroup({ t, values, disabled, permission, requestPermission, sendTest, set }) {
  const editable = disabled === false
  const on = values.browserNotifications !== false
  const row = (field, descriptionKey) => jsx(NotifyRow, {
    label: t(field),
    description: t(descriptionKey),
    checked: values[field] !== false,
    disabled: !editable || !on,
    onClick: () => set({ [field]: values[field] === false }),
    ariaLabel: t(field),
  })
  const permissionLabel = permission === 'granted'
    ? t('permissionGranted')
    : permission === 'denied' || permission === 'default' ? t('permissionDenied') : t('permissionUnavailable')
  return jsx(NotifyGroup, {
    title: t('groupBrowser'),
    children: [
      jsx(NotifyRow, {
        label: t('browserLabel'), description: t('browserDescription'), checked: on,
        disabled: !editable, onClick: () => set({ browserNotifications: !on }), ariaLabel: t('browserLabel'),
      }),
      row('notifyApproval', 'notifyApprovalDescription'),
      row('notifyQuestion', 'notifyQuestionDescription'),
      row('notifyPlanReview', 'notifyPlanReviewDescription'),
      row('notifyCompleted', 'notifyCompletedDescription'),
      row('notifyError', 'notifyErrorDescription'),
      jsx(NotifyRow, {
        label: t('backgroundOnly'), description: t('backgroundOnlyDescription'), checked: values.backgroundOnly !== false,
        disabled: !editable || !on, onClick: () => set({ backgroundOnly: values.backgroundOnly === false }), ariaLabel: t('backgroundOnly'),
      }),
      jsx(NotifyRow, {
        label: t('requireInteraction'), description: t('requireInteractionDescription'), checked: values.requireInteraction === true,
        disabled: !editable || !on, onClick: () => set({ requireInteraction: values.requireInteraction !== true }), ariaLabel: t('requireInteraction'),
      }),
      jsxs('div', {
        className: 'dshNotifyCard',
        children: [
          jsxs('div', {
            className: 'dshNotifyCopy',
            children: [
              jsx('div', { className: 'dshNotifyLabel', children: permissionLabel }),
              jsx('p', { className: 'dshNotifyDescription', children: t('browserDescription') }),
            ],
          }),
          jsxs('div', {
            className: 'dshNotifyActions',
            children: [
              jsx('button', {
                type: 'button', className: 'dshNotifyButton',
                disabled: permission === 'granted' || permission === 'unsupported',
                onClick: () => { Promise.resolve(requestPermission()).catch(() => {}) },
                children: t('grant'),
              }),
              jsx('button', {
                type: 'button', className: 'dshNotifyButton',
                disabled: permission !== 'granted',
                onClick: () => { sendTest() },
                children: t('test'),
              }),
            ],
          }),
        ],
      }),
    ],
  })
}

/** The keyword-rule editor. */
function RulesGroup({ t, values, disabled, set }) {
  const editable = disabled === false
  return jsx(NotifyGroup, {
    title: t('groupRules'),
    children: [
      jsxs('div', {
        className: 'dshNotifyCard',
        children: [
          jsxs('div', {
            className: 'dshNotifyCopy',
            children: [
              jsx('div', { className: 'dshNotifyLabel', children: t('keywordsLabel') }),
              jsx('p', { className: 'dshNotifyDescription', children: t('keywordsDescription') }),
              jsx('textarea', {
                className: 'dshNotifyField',
                value: typeof values.keywords === 'string' ? values.keywords : '',
                placeholder: t('keywordsPlaceholder'),
                disabled: !editable,
                spellCheck: false,
                'aria-label': t('keywordsLabel'),
                onChange: event => set({ keywords: event.target.value }),
              }),
            ],
          }),
        ],
      }),
    ],
  })
}

/** The section the Harness mounts under Settings → Notifications. */
function NotifySettingsSection({ t, useNotifySettings, set, requestPermission, sendTest }) {
  const snapshot = useNotifySettings(value => value)
  const values = resolveSettings(snapshot.value)
  const editable = snapshot.status === 'ready' && snapshot.writable && snapshot.mode === 'host'
  const disabled = !editable
  // The controls are disabled, but the write path is guarded too: a disabled
  // attribute only stops the browser's own event dispatch, and a write into a
  // read-only or process-local form must never be attempted from this page.
  const write = patch => { if (editable) set(patch) }
  const [permission, setPermission] = React.useState(() => (
    typeof Notification === 'undefined' ? 'unsupported' : Notification.permission
  ))
  return jsxs('section', {
    className: 'dshNotifySection',
    children: [
      jsx('h2', { className: 'dshNotifyHeading', children: t('title') }),
      jsx('p', { className: 'dshNotifyIntro', children: t('intro') }),
      jsx(NativeGroup, { t, values, disabled, status: snapshot, set: write }),
      jsx(BrowserGroup, {
        t, values, disabled, permission, set: write,
        requestPermission: () => Promise.resolve(requestPermission()).then(
          next => { setPermission(next ?? 'denied') },
          () => { setPermission('denied') },
        ),
        sendTest: () => {
          const result = sendTest()
          if (result?.ok === false) console.warn(`[dsh-notifications] test notification failed: ${result.message}`)
        },
      }),
      jsx(RulesGroup, { t, values, disabled, set: write }),
    ],
  })
}

    // ---- lib/client/entry.js ----
// The browser half's entry point: wire the runners, the settings section, and
// the locale dictionaries.
//
// Fragment: concatenated last by scripts/build-client.mjs; `apply` and
// `clientInject` are read off the factory's exports by the emitted wrapper.

/** The plugin id: package name, profile entry id, and client module id are one value. */
const CLIENT_ENTRY_ID = 'dsh-notifications'

/** Locale namespace owned by this plugin. */
const NOTIFY_LOCALE_NS = 'settings.dshNotifications'

/** Client services required before load. */
const clientInject = ['slots', 'locale', 'connection', 'configForms', 'sessions', 'uiSession']

/**
 * Show one decided attention, applying the visibility gate first.
 * @param ctx - the client context.
 * @param form - the profile settings form.
 * @param plan - the plan produced by the runner.
 * @returns the notifier result.
 */
function deliverNotification(ctx, form, plan) {
  const settings = resolveSettings(form.getSnapshot()?.value)
  const list = ctx.get('sessions')?.list
  const current = typeof list?.getSnapshot === 'function' ? list.getSnapshot()?.current : undefined
  const hidden = typeof document === 'undefined' ? false : document.hidden
  if (!shouldShowNotification(notificationPermission(), settings.backgroundOnly === true, hidden, plan.sessionId, current)) {
    return { ok: false, message: 'suppressed by permission or the background-only gate' }
  }
  return showNotification(plan.title, plan.body, plan.tag, plan.requireInteraction === true)
}

/** Mount the notification surface: runners, dictionaries, and the settings page. */
function apply(ctx) {
  adoptStyles()
  const t = ctx.locale.bind(NOTIFY_LOCALE_NS)
  ctx.effect(() => ctx.locale.register(NOTIFY_LOCALE_NS, dictionaries), 'dsh-notifications: dictionaries')

  const form = ctx.configForms.get(CLIENT_ENTRY_ID)
  const runner = startAttentionRunners({
    settings: form,
    uiSession: ctx.get('uiSession'),
    sessions: ctx.get('sessions'),
    translate: t,
    notify: plan => {
      const result = deliverNotification(ctx, form, plan)
      if (result.ok !== true) console.info(`[dsh-notifications] ${plan.kind} for ${plan.sessionId}: ${result.message}`)
    },
  })
  ctx.effect(() => () => runner.dispose(), 'dsh-notifications: attention runners')

  // A reconnect re-seeds the baseline: what happened while the transport was
  // down is history, and replaying it would fire a burst of stale banners.
  if (typeof ctx.on === 'function') {
    ctx.effect(() => ctx.on('connection/reset', () => { runner.reseed() }), 'dsh-notifications: reconnect reseed')
  }

  const requestPermission = () => Promise.resolve(requestNotificationPermission())
  const sendTest = () => showNotification(
    t('testTitle'),
    t('testBody'),
    `dsh-notifications-test-${Date.now()}`,
    false,
  )

  ctx.slots.inject('settings.section', () => ctx.slots.register({
    name: 'settings.section',
    id: 'notifications',
    order: 40,
    label: () => t('nav'),
    locale: NOTIFY_LOCALE_NS,
    inject: () => ({
      hooks: { notifySettings: form },
      set: patch => {
        for (const [field, value] of Object.entries(patch)) form.set(field, value)
      },
      requestPermission,
      sendTest,
    }),
  }, NotifySettingsSection))
}

    exports.inject = clientInject
    exports.apply = apply
    return module.exports
  },
})
