#!/usr/bin/env node
/**
 * Bundle the browser half into the committed `client.js`.
 *
 * Why a bundler instead of one big file: the host half and the browser half
 * share the same attention vocabulary and the same notification decision. That
 * logic lives once, in `lib/shared/`, and is inlined here — the bundle must not
 * carry a second copy that can drift.
 *
 * Why this bundler instead of esbuild: the published artifact stays byte-for-byte
 * what the repository contains, the package keeps zero dependencies, and the
 * transform is small enough to audit in one sitting. It accepts exactly the
 * subset the sources use — relative imports between bundled files, plain
 * `export` declarations, fragment files that declare nothing at all — and fails
 * loudly on anything else rather than emitting a broken bundle.
 *
 *   node scripts/build-client.mjs           # write client.js
 *   node scripts/build-client.mjs --check   # exit 1 when client.js is stale
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Concatenation order: a module may only use names declared before it. */
const MODULES = [
  'lib/shared/contract.js',
  'lib/shared/decision.js',
  'lib/client/notifier.js',
  'lib/client/runner.js',
  'lib/client/locales.js',
  'lib/client/styles.js',
  'lib/client/section.js',
  'lib/client/entry.js',
]

/** `import 'x'` — the side-effect form, which our sources never use. */
const IMPORT_SIDE_EFFECT = /^[ \t]*import\s*['"][^'"]+['"]\s*;?[ \t]*\r?\n/gm
/** `import … from 'x'` — one line or several, with an optional trailing comma. */
const IMPORT_STATEMENT = /^[ \t]*import\b[\s\S]*?from\s*['"][^'"]+['"]\s*;?[ \t]*\r?\n/gm
const EXPORT_LIST = /^[ \t]*export\s*\{[^}]*\}\s*;?[ \t]*\r?\n/gm
const EXPORT_PREFIX = /^[ \t]*export\s+(?=(?:async\s+)?(?:function|const|let|class)\b)/gm
const TOP_LEVEL_NAME = /^(?:async\s+)?(?:function|const|let|class)\s+([A-Za-z_$][\w$]*)/gm

/** Strip module syntax and collect the top-level names a file declares. */
function transform(source, file) {
  const stripped = source
    .replace(IMPORT_SIDE_EFFECT, '')
    .replace(IMPORT_STATEMENT, '')
    .replace(EXPORT_LIST, '')
    .replace(EXPORT_PREFIX, '')
  if (/^[ \t]*(?:import|export)\b/m.test(stripped)) {
    throw new Error(`${file}: unsupported module syntax (only plain exports and relative imports are bundled)`)
  }
  const names = [...stripped.matchAll(TOP_LEVEL_NAME)].map(match => match[1])
  return { stripped, names }
}

/** Build the bundle text. */
function build() {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))
  const parts = []
  const declared = new Map()
  for (const file of MODULES) {
    const { stripped, names } = transform(readFileSync(join(root, file), 'utf8'), file)
    for (const name of names) {
      const previous = declared.get(name)
      if (previous !== undefined) {
        throw new Error(`duplicate top-level name "${name}" in ${file} (already declared by ${previous})`)
      }
      declared.set(name, file)
    }
    parts.push(`    // ---- ${file} ----\n${stripped.trimEnd()}\n`)
  }
  return `// Generated by scripts/build-client.mjs from lib/** — do not edit by hand.\n`
    + `// Bundle id must equal the package name (the Harness keys the client module table by package name).\n`
    + `window.__ModuleLoader__.load({\n`
    + `  id: ${JSON.stringify(pkg.name)},\n`
    + `  factory: (require) => {\n`
    + `    const module = { exports: {} }\n`
    + `    const exports = module.exports\n`
    + `    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })\n`
    + `${parts.join('\n')}\n`
    + `    exports.inject = clientInject\n`
    + `    exports.apply = apply\n`
    + `    return module.exports\n`
    + `  },\n`
    + `})\n`
}

const bundle = build()
const target = join(root, 'client.js')
if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8')
  if (current !== bundle) {
    console.error('client.js is stale: run `npm run build:client`')
    process.exit(1)
  }
  console.log('client.js matches lib/**')
} else {
  writeFileSync(target, bundle)
  console.log(`client.js written (${bundle.length} bytes from ${MODULES.length} modules)`)
}
